version: '3.9'

services:
  postgres:
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: todo
    image: postgres:15.2-alpine

volumes:
  postgres-data:

networks:
  todo-dev:
    driver: bridge